# Automatically generated by hassfest.
#
# To update, run python3 -m script.hassfest -p docker
ARG BUILD_FROM
FROM ${BUILD_FROM}

# Synchronize with homeassistant/core.py:async_stop
ENV \
    S6_SERVICES_GRACETIME=240000 \
    UV_SYSTEM_PYTHON=true

ARG QEMU_CPU

# Install uv
RUN pip3 install uv==0.4.17

WORKDIR /usr/src
ENV UV_HTTP_TIMEOUT=3000
ENV HTTP_TIMEOUT=3000

#RUN uv pip install fnvhash==0.1.0
#RUN uv pip install pyric==0.1.6.3
#RUN uv pip install progettihwsw==0.1.3

## Setup KS Assistant Core dependencies
COPY requirements.txt homeassistant/
COPY homeassistant/package_constraints.txt homeassistant/homeassistant/
RUN \
    uv pip install -e true\
        --no-build \
        --upgrade \
        -r homeassistant/requirements.txt

COPY requirements_all.txt ks_assistant_frontend-* home_assistant_intents-* homeassistant/
#RUN uv pip install pyfronius==0.7.3
#RUN uv pip install pyqrcode==1.2.1
#RUN uv pip install pysyncthru==0.7.10
#RUN uv pip install pyturbojpeg==1.7.5

RUN \
    if ls homeassistant/home_assistant_*.whl 1> /dev/null 2>&1; then \
        uv pip install homeassistant/home_assistant_*.whl; \
    fi \
    && if ls homeassistant/ks_assistant_*.whl 1> /dev/null 2>&1; then \
        uv pip install homeassistant/ks_assistant_*.whl; \
    fi \
    && uv pip install \
        --no-build \
        --upgrade \
        -r homeassistant/requirements_all.txt

## Setup KS Assistant Core
COPY . homeassistant/
RUN \
    uv pip install \
        -e ./homeassistant \
    && python3 -m compileall \
        homeassistant/homeassistant

# KS Assistant S6-Overlay
COPY rootfs /

# Needs to be redefined inside the FROM statement to be set for RUN commands
ARG BUILD_ARCH
# Get go2rtc binary
RUN \
    case "${BUILD_ARCH}" in \
        "aarch64") go2rtc_suffix='arm64' ;; \
        "armhf") go2rtc_suffix='armv6' ;; \
        "armv7") go2rtc_suffix='arm' ;; \
        *) go2rtc_suffix=${BUILD_ARCH} ;; \
    esac \
    && curl -L https://github.com/AlexxIT/go2rtc/releases/download/v1.9.4/go2rtc_linux_${go2rtc_suffix} --output /bin/go2rtc \
    && chmod +x /bin/go2rtc \
    # Verify go2rtc can be executed
    && go2rtc --version

WORKDIR /config
